# the input directory where the source files are located
input_dir = "src"

# the output directory where the converted files will be saved
output_dir = "output"

# the filetype that should be extracted from the RTF file when using the `--extract` option
extract_filetype = "latex"

# list pf directories where additional files are located (e.g. images, bib files)
# separated by a : (colon), e.g. "images:resources"
# The current directory is always included; comment out if not needed
resource_paths = "resources"

# the path to the official template file converted to RTF
official_template = "./Tpl_Application Form (Part B) (HE MSCA PF).rtf"

# the string to be replaced in the official template file
string = "Insert here text for your proposal"

# by default, Pandoc will add a bibliography to each RTF section. By default, this tool
# will add citations as footnotes, so we can suppress the bibliography. If you use a different
# citation style, you may want to set this to False
suppress_bibliography = true

# insert the citation style path
# You can download styles from https://www.zotero.org/styles
citation_style = "./chicago-fullnote-bibliography-with-ibid.csl"

# Size for the footnotes in pt; if not set, the default size is 10pt
footnote_size = 9

# command to compile to PDF
# %f is substituted with the path to the compiled RTF 
# %o is substituted with the path to the compiled PDF
# Leave empty to turn off compilation to PDF
# pdf_compile = libreoffice --headless --convert-to pdf --outdir output %f"
